language: java
jdk: oraclejdk11

services:
 - mysql
before_install:
 - sudo mysql -e 'CREATE DATABASE pianyuan;'
 - sudo mysql -e 'select database();'
 - sudo mysql -e 'SHOW DATABASES;'
 - sudo mysql -e 'USE pianyuan;'
 - sudo mysql -e 'select database();'
 - sudo mysql --version

after_success: echo "I´m done"
