language: java
jdk: oraclejdk11

services:
 - mysql
before_install:
 - sudo mysql -e 'select User from mysql.user;'
 - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS calidad2;'
 - sudo mysql -e 'select database();'
 - sudo mysql -e 'USE calidad2;'
 - sudo mysql -e 'select database();'
 - sudo mysql -e 'CREATE TABLE IF NOT EXISTS calidad2.Alumno2(nombre VARCHAR(30), edad INT);'
 - sudo mysql -e 'SHOW TABLES from calidad2;'
 - sudo mysql --version

after_success: echo "Tablas creadas"
